// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtKb_wHC5RxnRCqJ1sFkTaMG5YKVmvrJQ',
    appId: '1:199671438254:web:94b3b2b4cff73ccc4b863f',
    messagingSenderId: '199671438254',
    projectId: 'to-do-list-2c800',
    authDomain: 'to-do-list-2c800.firebaseapp.com',
    storageBucket: 'to-do-list-2c800.firebasestorage.app',
    measurementId: 'G-F956CG217Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7EfKVahlITXjLM-btQmRCNPT4NpSMs8',
    appId: '1:199671438254:android:3bb6ed5c25d80b204b863f',
    messagingSenderId: '199671438254',
    projectId: 'to-do-list-2c800',
    storageBucket: 'to-do-list-2c800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhBFzvr18JCCfUnaLiF9WlcC_GOYcyPw',
    appId: '1:199671438254:ios:3a657e2bde160e824b863f',
    messagingSenderId: '199671438254',
    projectId: 'to-do-list-2c800',
    storageBucket: 'to-do-list-2c800.firebasestorage.app',
    iosBundleId: 'com.example.basicDesignProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnhBFzvr18JCCfUnaLiF9WlcC_GOYcyPw',
    appId: '1:199671438254:ios:3a657e2bde160e824b863f',
    messagingSenderId: '199671438254',
    projectId: 'to-do-list-2c800',
    storageBucket: 'to-do-list-2c800.firebasestorage.app',
    iosBundleId: 'com.example.basicDesignProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtKb_wHC5RxnRCqJ1sFkTaMG5YKVmvrJQ',
    appId: '1:199671438254:web:7d55e4180741c2c74b863f',
    messagingSenderId: '199671438254',
    projectId: 'to-do-list-2c800',
    authDomain: 'to-do-list-2c800.firebaseapp.com',
    storageBucket: 'to-do-list-2c800.firebasestorage.app',
    measurementId: 'G-BRZ523X4LF',
  );
}
